# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: mattallty/jest-github-action@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanoeb/jest-action@1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/vue/en/deploy/ to obtain it
          projectToken: ${{ secrets.STORYBOOK_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
